# Generated by Django 5.1.2 on 2024-10-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer', models.JSONField(default=list)),
                ('bufferSize', models.IntegerField(default=100)),
                ('in_index', models.IntegerField(default=0)),
                ('out_index', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('producerSleepTime', models.IntegerField(default=1000)),
                ('consumerSleepTime', models.IntegerField(default=1000)),
                ('shouldTerminate', models.BooleanField(default=False)),
                ('producerFinished', models.BooleanField(default=False)),
            ],
        ),
    ]
