# Generated by Django 5.1.2 on 2024-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerconsumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbuffer',
            name='bufferSize',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sharedbuffer',
            name='consumerSleepTime',
            field=models.IntegerField(default=0.6),
        ),
        migrations.AlterField(
            model_name='sharedbuffer',
            name='producerSleepTime',
            field=models.IntegerField(default=0.8),
        ),
    ]
