# Generated by Django 5.1.2 on 2024-10-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerconsumer', '0002_alter_sharedbuffer_buffersize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbuffer',
            name='consumerSleepTime',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='sharedbuffer',
            name='producerSleepTime',
            field=models.FloatField(default=0.8),
        ),
    ]
