# Generated by Django 5.1.2 on 2024-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerconsumer', '0004_taskoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbuffer',
            name='consumerSleepTime',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='sharedbuffer',
            name='producerSleepTime',
            field=models.FloatField(default=1.0),
        ),
    ]
